### ISSUE TITLE
Configure Docker build for bb

### ISSUE THREAD

**Issue by pcalcado** [BuoyantIO/bb#3]
Let's refer to the docker image as buoyantio/bb throughout and push it to dockerhub (drop the gcr.io part). I setup a dockerhub repo for you, here: https://hub.docker.com/r/buoyantio/bb/ . We should also configure auto builds for that repo.

**Comment by klingerf** [comment]
Ok, @siggy has enlightened me about automated builds:

* We can't add auto build to an existing repository -- we have to create it initially as an auto build repo

* Auto builds rely on the docker images being fully buildable from the Dockerfile alone. So the build process can't leverage the `docker-build-bb.sh` that we have in the repo.

If we want to setup auto build for this repo, then we need to:

* Re-create the repo on docker hub (not a problem)

* Switch to a multi-stage Dockerfile for building the image (somewhat unfortunate)

For new repositories, I feel like it's worth it to make them auto build, since that simplifies the release process a lot. @pcalcado, @siggy what are your thoughts? More info about auto build [here](https://docs.docker.com/docker-hub/builds/).
